### ISSUE TITLE
Supplies not being used but adding

### ISSUE THREAD

**Issue by HappyDie77** [taraniselsu/TacLifeSupport#105]
so i build a small space stastion orbiting kerbin but the food ,water and oxygen is going up by time for depleted its not going down like its suppose to do.

help

**Comment by taraniselsu** [comment]
This is a really old version and has not been updated in a long time.

See https://spacedock.info/mod/915/TAC%20Life%20Support instead. (also https://github.com/KSP-RO/TacLifeSupport or https://forum.kerbalspaceprogram.com/index.php?/topic/146465-112x-tac-life-support-v0180-release-19th-sep-2021/)
