### ISSUE TITLE
Resources not depleting

### ISSUE THREAD

**Issue by Bsd0** [taraniselsu/TacLifeSupport#43]
Hey, I just installed TAC life support exactly in the way the installation instructions said, except that the download came with no taclifesupport.dll. Now, when I launch a ship, it's food, water, etc, won't deplete. Nor will wastewater, etc, rise. 
![screenshot25](https://cloud.githubusercontent.com/assets/8862233/4357574/65b77f8c-4263-11e4-8ef0-5b5374f9bec4.png)
![screenshot28](https://cloud.githubusercontent.com/assets/8862233/4357575/65b8c748-4263-11e4-8f8d-338c1ce7ae13.png)
Thanks.

**Comment by taraniselsu** [comment]
I assume you figured this out and it was not a bug.
