### ISSUE TITLE
Add support for CKAN

### ISSUE THREAD

**Issue by Albarion** [taraniselsu/TacLifeSupport#59]
http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-5-0-24-Dec-2014

**Comment by taraniselsu** [comment]
Someone already wrote a netkan file for them. I just need to package an official release, and then someone will need to send them a pull request to _them_ with any necessary changes to the netkan file.

**Comment by johnpmayer** [comment]
Any timeline for the official release? Need help testing?

**Comment by taraniselsu** [comment]
See KSP-CKAN/NetKAN#597.

But also [see my post on the forums](http://forum.kerbalspaceprogram.com/threads/40667?p=1696858&viewfull=1#post1696858)
