### ISSUE TITLE
Support for Toolbar

### ISSUE THREAD

**Issue by Olympic1** [taraniselsu/TacLifeSupport#60]
Example can be found [here](https://github.com/TriggerAu/AlternateResourcePanel/blob/master/AlternateResourcePanel/SharedStuff/ToolbarWrapper.cs)

**Comment by taraniselsu** [comment]
I don't understand what you are asking for. This mod already works with [Blizzy's toolbar](http://forum.kerbalspaceprogram.com/threads/60863).

**Comment by Olympic1** [comment]
well, it doesn't show up on the toolbar. Already tried a fresh install of TAC LS and blizzy's toolbar. I will post pics soon

**Comment by jakkarth** [comment]
It doesn't just magically show up, you have to add the button to the toolbar using the toolbar's little down arrow and the Configure Visible Buttons option. I'm using TACLS with Blizzy in 0.90 without issue.

**Comment by Olympic1** [comment]
I know how it works, I play KSP since 0.19. But the icon doesn't show up in de list.

**Comment by taraniselsu** [comment]
Then you most likely have a mod conflict. I need a complete log file. Please read the [[Official] How To Get Support (READ FIRST)](http://forum.kerbalspaceprogram.com/threads/92229-How-To-Get-Support-%28READ-FIRST%29) thread for instructions on where to find the log file.

**Comment by Olympic1** [comment]
I solved the issue, somehow there was a file snuck into my KSP folder. After I deleted it the toolbar worked again.
