### ISSUE TITLE
BUG : kerbals on eva have no resources

### ISSUE THREAD

**Issue by Joshwoo69** [taraniselsu/TacLifeSupport#61]
Like food, waste etc.
kinda urgent bug. For got to post :P
Pics coming soonish.

**Comment by taraniselsu** [comment]
I need a complete log file and more information about what exactly is going wrong. Please read the [[Official] How To Get Support (READ FIRST)](http://forum.kerbalspaceprogram.com/threads/92229-How-To-Get-Support-%28READ-FIRST%29) thread for instructions on where to find the log file.

**Comment by Joshwoo69** [comment]
Log:
https://www.dropbox.com/s/ewj3qn36i2x6dsj/output_log.txt?dl=0

**Comment by Joshwoo69** [comment]
Fixed in latest version 0.90
