### ISSUE TITLE
Change MM patch to add EC rather than totally rewrite it

### ISSUE THREAD

**Issue by Wercho** [taraniselsu/TacLifeSupport#65]
Suggestion: This mostly applies to mod parts that have large amounts of EC and some crew. I rewrote MM_StockPartChanges.cfg to add 100 EC per crew, rather than changing the capacity to 100 EC per crew + 150. This way, modded parts keep their EC storage, and TAC LS just adds some extra.

```
// Change command pods to have 2 hours of electricity per crew member (only accounting for life support electricity needs)
@PART[*]:HAS[@MODULE[ModuleCommand],#CrewCapacity[*],~CrewCapacity[0]]:FOR[TacLifeSupport]
{
	@RESOURCE[ElectricCharge]
	{
		Baseamount = #$maxAmount$
		@maxAmount = 100
		@maxAmount *= #$/CrewCapacity$
		@maxAmount += #$Baseamount$ 
		@amount = #$maxAmount$
		!Baseamount = null
	}
}
```

**Comment by taraniselsu** [comment]
Done, though I changed it so that it only modifies stock parts. We'll have to see if there are mod parts that I need to do also, but it was catching a lot of parts that it should not have, like all the MKS/OKS parts.

**Comment by taraniselsu** [comment]
Changed by commit 6086b5521e5e6a42d9b09d497dc9dce1866cc154
