### ISSUE TITLE
Fix .version file in download

### ISSUE THREAD

**Issue by Olympic1** [taraniselsu/TacLifeSupport#83]
We were discussing on https://github.com/KSP-CKAN/NetKAN/issues/2830 to add the new TAC-LS version to CKAN using the `.version` file. But because of some compatibility listings in that file we needed to manually update the KSP version for this and future versions. If you could fix the version file for the next update, that would be greatly appriciated.

```
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 5
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 0
  },
  "KSP_VERSION_MAX": {
    "MAJOR": 1,
    "MINOR": -1,
    "PATCH": -1
  }
```

**Comment by taraniselsu** [comment]
I don't understand what you want me to change.

My current TacLifeSupport.version file is as follows:

```
{
  "NAME": "TAC Life Support",
  "URL": "http://ksp-avc.cybutek.net/version.php?id=9",
  "DOWNLOAD": "",
  "VERSION": "0.11.2.1",
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 5
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 0
  },
  "KSP_VERSION_MAX": {
    "MAJOR": 1,
    "MINOR": -1,
    "PATCH": -1
  }
}
```

Or are you referring to the values at KSP-AVC when it does the update check? If so, I'm sorry. I've been trying to get back to that.

**Comment by taraniselsu** [comment]
> Or are you referring to the values at KSP-AVC when it does the update check? ~~If so, I'm sorry. I've > been trying to get back to that.~~

Should be done now.

**Comment by Olympic1** [comment]
Yes, ckan now recognizes the `.version` file. Thx for fixing
