### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sviat9440** [taraniselsu/TacLifeSupport#95]
Kerbonauts do not use anything, in the console we see this:
![image](https://cloud.githubusercontent.com/assets/13107421/19830473/d8d6ecae-9e01-11e6-8f26-8bad95b78a6c.png)

KSP 1.2.0.1500

**Comment by JPLRepo** [comment]
KSP 1.2.0.1500?? is not the release version of KSP 1.2. It is a pre-release version.
I suggest you upgrade KSP to the release version.
You also don't mention what version of TAC LS you are using.
You have also raised this bug on taraniselsu's old repository.
Here is where the latest TAC LS is hosted.
https://github.com/KSP-RO/TacLifeSupport

**Comment by sviat9440** [comment]
I use TAC LC v0.12.5. Excuse me if I do not write back.

**Comment by JPLRepo** [comment]
?? Well that's pretty confusing.
a) good that you are using v0.12.5.. but as I pointed out. It is not from this repository. Link above.
b) with out a log, save file, or other info. Not a lot can be done to help.
c) as this isn't my repository. I can't close it.

**Comment by sviat9440** [comment]
I install KSP 1.2.0.1586, all is ok, thx
